bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]
# in debug mode, media files will be served using this configuration
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'
urlpatterns = [
    path('create/', views.create_image, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.image_detail, name='detail'),
    path('like/', views.like_image, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),

]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    # in order to keep the code generic, refering to the User model using AUTH_USER_MODEL setting instead directly refering to it
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            blank=True)
    url = models.URLField()
    # images will be uploaded to the specified folder in MEDIA_URL
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(db_index=True,
                                              default=0)

    # overriding the save() mathod to auto-generate the slug field based on the value of title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreationForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('url', 'title', 'description')
        widgets = {
            'url': forms.HiddenInput
        }

    # clean method for url to check whether it allows only JPG/JPEG or not(ends with .jpg or .jpeg)
    # this method will be executed on is_valid() call
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        # splitting once where a . is found, taking the [1]( second ) split, and make it lowercase
        extension = url.rsplit('.', 1)[1].lower()

        if extension not in valid_extensions:
            raise forms.ValidationError(
                'The given url does not match with valid image extensions')
        return url

    # overriding save() method to save the image when this method is called
    def save(self, force_insert=False,
             force_update=False,
             commit=True):

        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'

        # download image from the url
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from .forms import ImageCreationForm
from .models import Image
from django.http import JsonResponse, HttpResponse
from common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action
import redis
from django.conf import settings

# connecting to redis database
r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


@login_required
def create_image(request):
    if request.method == 'POST':
        form = ImageCreationForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # save the data and image in the object, but in the database
            new_item = form.save(commit=False)
            # add current user to the user of this item
            new_item.user = request.user
            # now save to db
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image has been sucessfully added')

            # redirect to new created item detail view
            return redirect(new_item.get_absolute_url())
    else:
        # fill the form with the GET data that contains url and title
        form = ImageCreationForm(data=request.GET)

    return render(request, 'images/image/create.html',
                  {'section': 'images',
                   'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # increment total view by 1 each time this view is called(page refreshed)
    redis_key = f'image:{image.id}:views'
    # object-type:id:field
    # incr() creates a key named 'views' for the image.id object
    # it creates 'views',because views is not an attribute of Image
    # if there was an attribute named 'views', that value would be incremented
    # it then increments the value of view,default is by 1
    total_views = r.incr(redis_key)

    # zincrby(name, amount, value)
    # increment the score of value(image.id) by amount(1) in a sorted set/dictionary, name(image_ranking)
    # image_rangking stores the value as image:rangking pair
    x = r.zincrby('image_ranking', 1, image.id)
    print(x)
    return render(request, 'images/image/detail.html',
                  {'section': 'images',
                   'image': image,
                   'total_views': total_views})


@ajax_required
@login_required
# allow only POST request, returns 405(HttpResponseNotAllowed) otherwise
@require_POST
def like_image(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                # adds only once if already exists
                image.users_like.add(request.user)
            else:
                # removes if exists, does nothing otherwise
                image.users_like.remove(request.user)
                create_action(request.user, 'likes', image)

            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'error'})


# view to list all bookmarked inages
@login_required
def image_list(request):
    images = Image.objects.all()
    # PAGINATOR
    paginator = Paginator(images, 6)
    page = request.GET.get('page')

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # First page
        images = paginator.page(1)
    except EmptyPage:
        # if page object is is out of range and
        if request.is_ajax():
            # if request is ajax, return empty page to stop ajax pagination on browser
            return HttpResponse('')
        # if page is out of range but request is not ajax, deliver last page
        images = paginator.page(paginator.num_pages)

    # if request is ajax, but not out of page, deliver ajax paginated list
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'section': 'images', 'images': images})

    # if not ajax request, deliver standard paginated list
    return render(request,
                  'images/image/list.html',
                  {'section': 'images', 'images': images})


#
@login_required
def image_ranking(request):
    # getting image:ranking(image_ranking) dictionary
    # zrange(name, start, end, desc)
    # raturn a range of value from the sorted set image_ranking, between start and end
    # -1 means end of the range
    image_ranking = r.zrange('image_ranking', 0, -1,
                             desc=True)[:10]
    print(image_ranking)
    image_ranking_ids = [int(id) for id in image_ranking]
    print(image_ranking_ids)
    # get most viewed images
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    print(most_viewed)
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    print(most_viewed)
    return render(request,
                  'images/image/ranking.html',
                  {'section': 'images',
                   'most_viewed': most_viewed})

images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %} Bookmark an Image {% endblock title%}

{% block content %}
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form action="" method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
</form>
{% endblock content%}

images/templates/images/image/detail.html
{% extends 'base.html' %}

{% block title %} {{ image.title }} {% endblock %}

{% block content %}
<h1>{{ image.title }}</h1>
<!-- using thumnail tags to display thumbnail of the image rather than the actual image-->
{% load thumbnail %}
<a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 300x0 quality=100 %}" alt="{{ image.title }} url" class="image-detail">
</a>

{% with total_likes=image.users_like.count users_like=image.users_like.all %}
<div class="image-info">
    <div>
        <span class="count">
            <span class="total">{{ total_likes }} like{{ total_likes|pluralize}} </span>
        </span>
        <span class="count">
            {{ total_views }} view{{ total_views|pluralize}}
        </span>
        <!-- adding id and action attributes to the <a> tag of this image for sending to view -->
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"
            class="like button">
            {% if request.user not in users_like %}
            Like
            {% else %}
            Unlike
            {% endif %}
        </a>
    </div>
    {{ image.description|linebreaks }}
</div>
<div class="image-likes">
    {% for user in users_like %}
    <div>
        <img src="{{ user.profile.photo.url }}" alt="">
        <p>{{ user.first_name }}</p>
    </div>
    {% empty %}
    There is no likes yet
    {% endfor %}
</div>
{% endwith %}
{% endblock %}
{% block domready %}
$('a.like').click(function(e){

e.preventDefault();
$.post('{% url "images:like" %}',
{
id: $(this).data('id'),
action: $(this).data('action')
},
function(data){
if (data['status'] == 'ok')
{
var previous_action = $('a.like').data('action');

// toggle data-action
$('a.like').data('action', previous_action == 'like' ?
'unlike' : 'like');
// toggle link text
$('a.like').text(previous_action == 'like' ? 'Unlike' :
'Like');

// update total likes
var previous_likes = parseInt($('span.count .total').text());
$('span.count .total').text(previous_action == 'like' ?
previous_likes + 1 : previous_likes - 1);
}
}
);
});
{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
<h1>Images bookmarked</h1>
<div id="image-list">
    {% include "images/image/list_ajax.html" %}
    <!-- images will be appended here via ajax request -->
</div>
{% endblock %}

{% block domready %}
<!-- current page number -->
var page = 1;
<!-- allows to know if user is on last page -->
var empty_page = false;
<!-- prevents sending repeated ajax request when one request is processing -->
var block_request = false;
<!-- to capture scroll event -->
$(window).scroll(function() {
<!-- finding out remaining margin to scroll -->
var margin = $(document).height() - $(window).height() - 200;
<!-- if the user is not on last page and no other ajax request is processing-->
if($(window).scrollTop() > margin && empty_page == false &&
block_request == false) {
<!-- start processing this ajax request -->
block_request = true;
<!-- retrieve the next page -->
page += 1;
<!-- the AJAX request -->
$.get('?page=' + page, function(data) {
<!-- if there is no data, there is no more page to load. so set it empty page -->
if(data == '') {
empty_page = true;
}
<!-- if there are pages to load -->
else {
<!-- indicate that this process is done -->
block_request = false;
<!-- append all the data(images) to html elemend of class 'image-list' -->
$('#image-list').append(data);
}
});
}
});
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
<div class="image">
    <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{ image.get_absolute_url }}">
            <img src="{{ im.url }}">
        </a>
    </a>
    <div class="info">
        <a href="{{ image.get_absolute_url }}" class="title">
            {{ image.title }}
        </a>
    </div>
</div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends 'base.html' %}
{% block title %} Image Top chart {% endblock title %}

{% block content %}
<h1>Image Topchart</h1>
<ol>
    {% for image in most_viewed %}
    <li>
        <a href=" {{ image.get_absolute_url }}"> {{ image.title }}</a>
    </li>
    {% endfor %}
</ol>
{% endblock content %}